# Generated by Django 4.0.2 on 2022-03-28 12:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APPSkrift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('evaluationId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stars', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default='E', max_length=1)),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
                ('dateMade', models.DateField(auto_now_add=True)),
                ('cousine', models.CharField(choices=[('Europeisk', 'Europeisk'), ('Asiatisk', 'Asiatisk'), ('Fransk', 'Fransk'), ('Amerikansk', 'Amerikansk'), ('Indisk', 'Indian'), ('Annet', 'Annet')], default='Annet', max_length=255)),
                ('estimate', models.CharField(choices=[('15 min', '15 min'), ('30 min', '30 min'), ('45 min', '45 min'), ('1 time', '1 hour'), ('Over 1 time', 'Over 1 time')], default='15 min', max_length=255)),
                ('meal', models.CharField(choices=[('Frokost', 'Frokost'), ('Lunsj', 'Lunsj'), ('Middag', 'Middag')], default='Middag', max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='recipe_images')),
                ('avgEvaluation', models.FloatField(blank=True, default=0, null=True)),
                ('nbOfLikes', models.IntegerField(blank=True, default=0)),
                ('categories', models.ManyToManyField(blank=True, related_name='categories', to='APPskrift.Category')),
                ('evaluations', models.ManyToManyField(blank=True, to='APPskrift.Evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('darkMode', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='profile_images')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorite', to='APPskrift.Recipe')),
                ('saved', models.ManyToManyField(blank=True, related_name='saved', to='APPskrift.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='publishedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APPskrift.user'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evalRecipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPskrift.recipe'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='publishedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPskrift.user'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('dateTimeMade', models.DateTimeField(auto_now_add=True)),
                ('publishedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPskrift.user')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPskrift.recipe')),
            ],
        ),
    ]
