# Generated by Django 4.0.2 on 2022-02-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPskrift', '0003_category_recipe_user_recipe_publishedby_evaluation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorits',
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(to='APPskrift.Recipe'),
        ),
    ]
