# Generated by Django 4.0.2 on 2022-02-10 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APPskrift', '0003_category_recipe_user_recipe_publishedby_evaluation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favorits',
            new_name='favorites',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='APPskrift.category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='publishedBy',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='APPskrift.user'),
        ),
    ]
