# Generated by Django 4.0.2 on 2022-02-15 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPskrift', '0004_remove_user_favorits_user_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='publishedBy',
        ),
        migrations.RenameField(
            model_name='evaluation',
            old_name='user',
            new_name='publishedBy',
        ),
    ]
