# Generated by Django 4.0.2 on 2022-02-10 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APPskrift', '0007_alter_recipe_category_alter_recipe_publishedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APPskrift.category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='publishedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APPskrift.user'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorites',
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(to='APPskrift.Recipe'),
        ),
    ]
