# Generated by Django 4.0.2 on 2022-02-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPskrift', '0008_alter_recipe_category_alter_recipe_publishedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='APPskrift.Recipe'),
        ),
    ]
