# Generated by Django 4.0.2 on 2022-02-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPskrift', '0009_alter_user_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='saved', to='APPskrift.Recipe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite', to='APPskrift.Recipe'),
        ),
    ]
